/**
 * API Surface Snapshot Tests
 *
 * These tests verify the public API surface of each foundation package
 * has not changed accidentally. For each package, we import everything
 * and verify the exported names match a known list. Only value exports
 * (functions, classes, constants) are checked since type-only exports
 * do not appear in runtime Object.keys().
 */
import { describe, it, expect } from 'vitest';

describe('API Surface Tests', () => {

  // ─── @grith/crypto ──────────────────────────────────────────────────────────

  it('@grith/crypto exports', async () => {
    const mod = await import('@grith/crypto');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'KeyManager',
      'base64urlDecode',
      'base64urlEncode',
      'canonicalizeJson',
      'constantTimeEqual',
      'fromHex',
      'generateId',
      'generateKeyPair',
      'generateNonce',
      'keyPairFromPrivateKey',
      'keyPairFromPrivateKeyHex',
      'sha256',
      'sha256Object',
      'sha256String',
      'sign',
      'signString',
      'timestamp',
      'toHex',
      'verify',
    ].sort());
  });

  // ─── @grith/ccl ─────────────────────────────────────────────────────────────

  it('@grith/ccl exports', async () => {
    const mod = await import('@grith/ccl');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'CCLSyntaxError',
      'CCLValidationError',
      'checkRateLimit',
      'evaluate',
      'evaluateCondition',
      'matchAction',
      'matchResource',
      'merge',
      'parse',
      'parseTokens',
      'serialize',
      'specificity',
      'tokenize',
      'validateNarrowing',
    ].sort());
  });

  // ─── @grith/core ────────────────────────────────────────────────────────────

  it('@grith/core exports', async () => {
    const mod = await import('@grith/core');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'CovenantBuildError',
      'CovenantVerificationError',
      'DocumentMigrator',
      'MAX_CHAIN_DEPTH',
      'MAX_CONSTRAINTS',
      'MAX_DOCUMENT_SIZE',
      'MemoryChainResolver',
      'PROTOCOL_VERSION',
      'buildCovenant',
      'canonicalForm',
      'computeEffectiveConstraints',
      'computeId',
      'countersignCovenant',
      'defaultMigrator',
      'deserializeCovenant',
      'resignCovenant',
      'resolveChain',
      'serializeCovenant',
      'validateChainNarrowing',
      'validateChainSchema',
      'validateConstraintsSchema',
      'validateDocumentSchema',
      'validatePartySchema',
      'verifyCovenant',
    ].sort());
  });

  // ─── @grith/store ───────────────────────────────────────────────────────────

  it('@grith/store exports', async () => {
    const mod = await import('@grith/store');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'FileStore',
      'IndexedStore',
      'MemoryStore',
      'QueryBuilder',
      'SqliteStore',
      'StoreIndex',
      'createQuery',
      'createTransaction',
    ].sort());
  });

  // ─── @grith/types ───────────────────────────────────────────────────────────

  it('@grith/types exports', async () => {
    const mod = await import('@grith/types');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'ActiveSpan',
      'CCLError',
      'ChainError',
      'CircuitBreaker',
      'Counter',
      'CryptoError',
      'DEFAULT_SEVERITY',
      'DocumentedErrorCode',
      'DocumentedGrithError',
      'Gauge',
      'HealthChecker',
      'Histogram',
      'InMemoryCollector',
      'LogLevel',
      'Logger',
      'MetricsRegistry',
      'GRITH_VERSION',
      'SUPPORTED_HASH_ALGORITHMS',
      'SUPPORTED_SIGNATURE_SCHEMES',
      'GrithError',
      'GrithErrorCode',
      'StorageError',
      'Tracer',
      'ValidationError',
      'assertNever',
      'createDebugLogger',
      'createLogger',
      'createMetricsRegistry',
      'createTracer',
      'debug',
      'defaultLogger',
      'defaultMetrics',
      'deprecated',
      'err',
      'errorDocsUrl',
      'formatError',
      'freezeDeep',
      'getEmittedWarnings',
      'isDebugEnabled',
      'isNonEmptyString',
      'isPlainObject',
      'isValidHex',
      'isValidISODate',
      'isValidId',
      'isValidPublicKey',
      'isValidSignature',
      'isValidVersion',
      'ok',
      'resetDeprecationWarnings',
      'sanitizeJsonInput',
      'sanitizeString',
      'validateHex',
      'validateNonEmpty',
      'validateProbability',
      'validateRange',
      'withRetry',
      'wrapDeprecated',
    ].sort());
  });

  // ─── @grith/identity ────────────────────────────────────────────────────────

  it('@grith/identity exports', async () => {
    const mod = await import('@grith/identity');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'AdaptiveCarryForward',
      'DEFAULT_EVOLUTION_POLICY',
      'IdentityCommitment',
      'IdentitySimilarity',
      'LineageCompactor',
      'SelectiveDisclosure',
      'SemanticVersion',
      'completeReverification',
      'computeCapabilityManifestHash',
      'computeCarryForward',
      'computeDecayedTrust',
      'computeIdentityHash',
      'createIdentity',
      'deserializeIdentity',
      'evolveIdentity',
      'getLineage',
      'serializeIdentity',
      'shareAncestor',
      'triggerReverification',
      'verifyCompositeProof',
      'verifyIdentity',
    ].sort());
  });

  // ─── @grith/verifier ────────────────────────────────────────────────────────

  it('@grith/verifier exports', async () => {
    const mod = await import('@grith/verifier');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'Verifier',
      'verifyBatch',
    ].sort());
  });

  // ─── @grith/enforcement ─────────────────────────────────────────────────────

  it('@grith/enforcement exports', async () => {
    const mod = await import('@grith/enforcement');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'AuditChain',
      'CapabilityError',
      'CapabilityGate',
      'Monitor',
      'MonitorDeniedError',
      'addDefenseLayer',
      'analyzeDefense',
      'buildProvenanceChain',
      'createDefenseConfig',
      'createProvenanceRecord',
      'disableLayer',
      'queryProvenance',
      'verifyMerkleProof',
      'verifyProvenance',
    ].sort());
  });

  // ─── @grith/sdk ─────────────────────────────────────────────────────────────

  it('@grith/sdk exports', async () => {
    const mod = await import('@grith/sdk');
    const exports = Object.keys(mod).sort();
    expect(exports).toEqual([
      'AGENT_KEY_SCHEMA',
      'AdaptiveAlignmentTracker',
      'AlignmentFeedbackLoop',
      'AlignmentSurface',
      'AuditChain',
      'BreachStateMachine',
      'CATALOGS',
      'CCLSyntaxError',
      'CCLValidationError',
      'CCL_EVALUATION_CONTEXT_SCHEMA',
      'CERTIFICATION_REQUIREMENTS',
      'COMPLIANCE_STANDARDS',
      'CONFIGURATION_PATH',
      'COVENANT_SCHEMA',
      'CapabilityError',
      'CapabilityGate',
      'ComplianceSurface',
      'ComplianceTrajectory',
      'ConcessionProtocol',
      'ContinuousTrigger',
      'CovenantBuildError',
      'CovenantVerificationError',
      'DEFAULT_EVOLUTION_POLICY',
      'DEFAULT_GOVERNANCE_BOOTSTRAP',
      'DEFAULT_SCORING_CONFIG',
      'DISCOVERY_DOCUMENT_SCHEMA',
      'DecayModel',
      'DiscoveryClient',
      'DiscoveryServer',
      'DriftForecaster',
      'DynamicQuorum',
      'ExponentialDegradation',
      'FIELD_PRIME',
      'FileStore',
      'FitnessEvolution',
      'GraduatedBurner',
      'IncrementalParetoFrontier',
      'IndexedStore',
      'JURISDICTIONS',
      'JurisdictionConflictResolver',
      'KeyManager',
      'MAX_CHAIN_DEPTH',
      'MAX_CONSTRAINTS',
      'MAX_DOCUMENT_AGE_MS',
      'MAX_DOCUMENT_SIZE',
      'MemoryChainResolver',
      'MemoryStore',
      'MiddlewarePipeline',
      'Monitor',
      'MonitorDeniedError',
      'NoopCounter',
      'NoopHistogram',
      'NoopMeter',
      'NoopSpan',
      'NoopTracer',
      'PROTOCOL_VERSION',
      'PhaseTransitionDetector',
      'PipelineSimulator',
      'PropertyAnomalyDetector',
      'QueryBuilder',
      'QuickCovenant',
      'QuorumIntersectionVerifier',
      'ReceiptDAG',
      'RecoveryModel',
      'RegulatoryImpactAnalyzer',
      'RemediationPlanner',
      'RepeatOffenderDetector',
      'ReputationAggregator',
      'ReputationDecayModel',
      'STAKE_TIERS',
      'STANDARD_ALIGNMENT_PROPERTIES',
      'STANDARD_METRICS',
      'GRITH_MEDIA_TYPE',
      'SUBSTRATE_DEFAULTS',
      'SpanStatusCode',
      'SqliteStore',
      'GrithAccessDeniedError',
      'GrithCallbackHandler',
      'GrithClient',
      'GrithMetrics',
      'StoreIndex',
      'StreamlinedBFT',
      'StressResponseCurve',
      'TRANSLATION_KEYS',
      'TRUST_IDENTITY',
      'TRUST_ZERO',
      'TemporalConstraintAlgebra',
      'TrustGraph',
      'Verifier',
      'ViolationForecaster',
      'WELL_KNOWN_PATH',
      'addDefenseLayer',
      'addLayer',
      'addMetric',
      'addResolver',
      'addTranslation',
      'adoptAntibody',
      'aggregateData',
      'aggregateFees',
      'aggregateGatewayMetrics',
      'aggregateMetric',
      'agree',
      'alignmentDecomposition',
      'alignmentDrift',
      'alignmentGap',
      'allocateTrust',
      'analyzeDefense',
      'analyzeImpossibilityBounds',
      'analyzeNorms',
      'analyzeTier',
      'analyzeTrajectory',
      'anonymizeDataset',
      'antibodyExists',
      'antifragilityIndex',
      'applyImprovement',
      'assessAlignment',
      'assessConditionalRisk',
      'assessRisk',
      'assessSeverity',
      'assignTier',
      'attestationChainVerify',
      'auditTrailExport',
      'authMiddleware',
      'base64urlDecode',
      'base64urlEncode',
      'blackScholesPrice',
      'buildCovenant',
      'buildDiscoveryDocument',
      'buildEntanglementNetwork',
      'buildGovernanceDashboard',
      'buildKeyEntry',
      'buildKeySet',
      'buildProvenanceChain',
      'burnDelegation',
      'burnStake',
      'byzantineFaultTolerance',
      'cachingMiddleware',
      'calculateFee',
      'calculateRevenueLift',
      'calibratedAntifragilityIndex',
      'canEvolve',
      'canaryCorrelation',
      'canarySchedule',
      'canonicalForm',
      'canonicalizeJson',
      'cclConformance',
      'checkPhysicalConstraint',
      'checkRateLimit',
      'checkSafetyBound',
      'claimPolicy',
      'coBurnDelegation',
      'coalitionStability',
      'collateralizationRatio',
      'compareProfiles',
      'compareTiers',
      'completeReverification',
      'completeTransaction',
      'compose',
      'compositionComplexity',
      'computeAccountability',
      'computeAttestationCoverage',
      'computeAuditCommitment',
      'computeCapabilityManifestHash',
      'computeCarryForward',
      'computeConstraintCommitment',
      'computeDecaySchedule',
      'computeDecayedTrust',
      'computeEffectiveConstraints',
      'computeGovernanceVote',
      'computeId',
      'computeIdentityHash',
      'computeNPartyNash',
      'computeNashBargainingSolution',
      'computeProfile',
      'computeRailVolume',
      'computeReceiptsMerkleRoot',
      'computeReputationScore',
      'computeTrends',
      'computeTrustTransitivity',
      'computeVotingPower',
      'consensusLatency',
      'constantTimeEqual',
      'constraintTranslation',
      'counter',
      'countersignCovenant',
      'countersignReceipt',
      'covenantConformance',
      'createAccount',
      'createAdapter',
      'createAttestation',
      'createAuthority',
      'createBreachAttestation',
      'createChainGuard',
      'createComplianceMonitor',
      'createCovenantRouter',
      'createDashboard',
      'createDefenseConfig',
      'createDelegation',
      'createEndorsement',
      'createEntanglement',
      'createFederationConfig',
      'createFeeSchedule',
      'createFuture',
      'createGateway',
      'createGovernancePolicy',
      'createIdentity_core',
      'createIncidentReport',
      'createLedger',
      'createMarketplace',
      'createMarketplaceTransaction',
      'createMetaCovenant',
      'createPlaybook',
      'createPolicy',
      'createProvenanceRecord',
      'createQuery',
      'createRail',
      'createReceipt',
      'createResourcePool',
      'createStake',
      'createStakedAgent',
      'createStandardDashboard',
      'createTelemetry',
      'createToolGuard',
      'createTransaction',
      'createTrustGate',
      'crossJurisdictionCompliance',
      'cryptoConformance',
      'decomposeCovenants',
      'defineAlignment',
      'defineConjecture',
      'defineEvolution',
      'defineSafetyEnvelope',
      'deserializeCovenant',
      'deserializeIdentity',
      'detectionProbability',
      'disableLayer',
      'discoverNorms',
      'disputeTransaction',
      'escalateIncident',
      'evaluateAccess',
      'evaluateCCL',
      'evaluateCanary',
      'evaluateCondition',
      'evaluateCounterparty',
      'evaluateNegotiation',
      'evaluatePhaseTransition',
      'evaluateTriggers',
      'evolutionHistory',
      'evolve',
      'evolveIdentity_core',
      'executeRailTransaction',
      'executeWithRetry',
      'expectedCostOfBreach',
      'expirationForecast',
      'exportLegalPackage',
      'failNegotiation',
      'fieldToHex',
      'findConflicts',
      'findMinimalVerificationSet',
      'forceAdopt',
      'formalVerification',
      'fromHex',
      'fuzz',
      'generateAdversarialInputs',
      'generateAntibody',
      'generateCanary',
      'generateComplianceProof',
      'generateComplianceReport',
      'generateId',
      'generateKeyPair',
      'generateNonce',
      'generateRegulatoryReport',
      'generateTemplate',
      'getAccountSummary',
      'getPreset',
      'getAllSchemas',
      'getDefaultLocale',
      'getDiscrepancies',
      'getLineage',
      'getStandardConjectures',
      'getSupportedLocales',
      'hashToField',
      'hedgeRatio',
      'honestyMargin',
      'initializeGovernance',
      'initiateNegotiation',
      'initiateRailTransaction',
      'interopConformance',
      'intersectConstraints',
      'isCanaryExpired',
      'isNegotiationExpired',
      'isResourceAllowed',
      'isSigned',
      'issueCertificate',
      'keyPairFromPrivateKey',
      'keyPairFromPrivateKeyHex',
      'listAgent',
      'listPresets',
      'loggingMiddleware',
      'mapToJurisdiction',
      'matchAction',
      'matchIncident',
      'matchResource',
      'mechanismDesign',
      'mergeCCL',
      'metricsMiddleware',
      'minimumDetection',
      'minimumStake',
      'modelPrincipalAgent',
      'networkAccountabilityRate',
      'networkHealth',
      'normConflictDetection',
      'normPrecedence',
      'paretoFrontier',
      'parseCCL',
      'parseTokens',
      'physicalCovenant',
      'poseidonHash',
      'priceInsurance',
      'processPayment',
      'processRequest',
      'projectRevenue',
      'propose',
      'proposeImprovement',
      'proposeStandard',
      'proposeToGovernance',
      'protect',
      'proveAlgebraicProperties',
      'proveHonesty',
      'proveRobustness',
      'proveSystemProperty',
      'proveTermination',
      'pruneOldData',
      'quarantineAgent',
      'queryProvenance',
      'quorumSize',
      'rateLimitMiddleware',
      'reconcile',
      'recordQuery',
      'recordQueryIncome',
      'registerGovernanceAgent',
      'registerJurisdiction',
      'regulatoryGapAnalysis',
      'rejectAntibody',
      'releaseStake',
      'releaseTrust',
      'removeResolver',
      'repeatedGameEquilibrium',
      'resignCovenant',
      'resolveAgent',
      'resolveChain_core',
      'resolveIncident',
      'retryMiddleware',
      'revokeCertificate',
      'robustnessScore',
      'rollbackRailTransaction',
      'roundCount',
      'runConformanceSuite',
      'runZeuthenNegotiation',
      'searchMarketplace',
      'securityConformance',
      'selectOptimalResolvers',
      'serializeCCL',
      'serializeCovenant',
      'serializeIdentity',
      'setDefaultLocale',
      'settleFuture',
      'sha256',
      'sha256Object',
      'sha256String',
      'shareAncestor',
      'sign',
      'signAttestation',
      'signString',
      'slashStake',
      'specificity',
      'grithGuardHandler',
      'grithMiddleware',
      'stressTest',
      'substrateCapabilityMatrix',
      'substrateCompatibility',
      't',
      'takeSnapshot',
      'telemetryMiddleware',
      'tierToMinScore',
      'timestamp',
      'timingMiddleware',
      'toHex',
      'tokenize',
      'transitionPhase',
      'translateCovenant',
      'triggerReverification',
      'trustBase',
      'trustCompose',
      'trustIntersect',
      'trustInverse',
      'trustNegate',
      'trustTensorProduct',
      'unquarantineAgent',
      'updateAgentStatus',
      'validateAgentKeySchema',
      'validateChainNarrowing',
      'validateComposition',
      'validateConsensusConfig',
      'validateConsensusPolicy',
      'validateCovenantSchema',
      'validateDiscoveryDocument',
      'validateDiscoverySchema',
      'validateGameTheoryParameters',
      'validateNarrowing',
      'validateProtocolData',
      'validationMiddleware',
      'valueAtRisk',
      'verify',
      'verifyAttestation',
      'verifyBatch',
      'verifyBreachAttestation',
      'verifyCertificate',
      'verifyComplianceProof',
      'verifyCovenant_core',
      'verifyEndorsement',
      'verifyEntangled',
      'verifyEnvelopeIntegrity',
      'verifyIdentity',
      'verifyMerkleProof',
      'verifyProvenance',
      'verifyReceipt',
      'verifyReceiptChain',
      'verifyRecursively',
      'voteForAntibody',
      'withGrith',
      'withGrithTool',
      'withGrithTools',
      'zeuthenStrategy',
    ].sort());
  });

  // ─── Cross-package consistency checks ───────────────────────────────────────

  describe('Cross-package consistency', () => {

    it('PROTOCOL_VERSION is consistent across core and sdk', async () => {
      const core = await import('@grith/core');
      const sdk = await import('@grith/sdk');
      expect(core.PROTOCOL_VERSION).toBe(sdk.PROTOCOL_VERSION);
    });

    it('MAX_CHAIN_DEPTH is consistent across core and sdk', async () => {
      const core = await import('@grith/core');
      const sdk = await import('@grith/sdk');
      expect(core.MAX_CHAIN_DEPTH).toBe(sdk.MAX_CHAIN_DEPTH);
    });

    it('buildCovenant is the same function in core and sdk', async () => {
      const core = await import('@grith/core');
      const sdk = await import('@grith/sdk');
      expect(core.buildCovenant).toBe(sdk.buildCovenant);
    });

    it('generateKeyPair is the same function in crypto and sdk', async () => {
      const crypto = await import('@grith/crypto');
      const sdk = await import('@grith/sdk');
      expect(crypto.generateKeyPair).toBe(sdk.generateKeyPair);
    });

    it('parse from ccl is the same function as parseCCL from sdk', async () => {
      const ccl = await import('@grith/ccl');
      const sdk = await import('@grith/sdk');
      expect(ccl.parse).toBe(sdk.parseCCL);
    });
  });
});
